server:
 port: 8090

spring:
#  application#    name: store-manager
  
  servlet:
    #multipart 파일처리 조건
    multipart:
      max-file-size: -1
      max-request-size: -1
  #database 접속 정보
  datasource:
         #jdbc:mysql://엔드포인트/데이터베이스?옵션...    url: jdbc:mysql://mysql-1.cnljqyjrs4qx.ap-northeast-2.rds.amazonaws.com/storemanager?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: admin
    password: password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    show-sql: true # 데이터 처리할 때 SQL문을 보여줌
    generate-ddl: true # 클래스 정의에 따른 테이블 및 객체 생성
    properties:
      hibernate:
        jdbc:
          batch_size: 5
        order_inserts: true
        order_updates: true
        generate_statistics: true
  rabbitmq:
    host: ec2-13-124-232-201.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123

api:
   base-path: http://localhost:8090
   
---
spring:
  profiles: prod    
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.0.24:8761/eureka/
#  instance:
#    hostname: 192.168.0.23

api:
  base-path: 


